### PR TITLE
Deregister register bug

### LINKED ISSUE #119: Consul-ESM: External node checks disappear after re-registration of nodes
**Describe the bug**
Consul ESM shows no node checks after re-registering nodes.

**To Reproduce**
Following the [Learning Guide] (https://learn.hashicorp.com/tutorials/consul/service-registration-external-services?in=consul/developer-discovery) I build my setup. Tried following steps:-

* Started Consul agent in -dev mode.
* Register an external service to consul with health checks by running command `curl --request PUT --data @external.json localhost:8500/v1/catalog/register`, refer to the configuration of external service file. 

```
$ cat external.json

{
  "Node": "External-Node",
  "Address": "192.168.64.32",
  "NodeMeta": {
    "external-node": "true",
    "external-probe": "true"
  },
  "Service": {
    "ID": "Python-HTTP",
    "Service": "Python",
    "Port": 80
  },
  "Checks": [
    {
      "Name": "tcp-check",
      "status": "critical",
      "Definition": {
        "TCP": "192.168.64.32:80",
        "interval": "30s"
      },
      "ServiceID": "Python-HTTP",
      "CheckID": "service:Python"
    }
  ]
}

```

* Started consul-esm agent, initially it perform health checks for node "External-Node" and on Consul UI status of both service and node was okay.

```
$ curl localhost:8500/v1/health/node/External-Node
[
    {
        "Node": "External-Node",
        "CheckID": "externalNodeHealth",
        "Name": "External Node Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Node alive or reachable",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Type": "",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {},
        "CreateIndex": 29,
        "ModifyIndex": 160
    },
    {
        "Node": "External-Node",
        "CheckID": "service:Python",
        "Name": "tcp-check",
        "Status": "passing",
        "Notes": "",
        "Output": "TCP connect 192.168.64.32:80: Success",
        "ServiceID": "Python-HTTP",
        "ServiceName": "Python",
        "ServiceTags": [],
        "Type": "",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {
            "Interval": "30s",
            "TCP": "192.168.64.32:80"
        },
        "CreateIndex": 24,
        "ModifyIndex": 2963
    }
]

```

* Once we deregister node and re-register it back, Consul-ESM agent could not update the health check status and flagging node check as "No health check". 

```
$ cat external-node-deregister.json 

{
 "Node": "External-Node"
}
```

**De-Registering Node**

` $ curl --request PUT --data @external-node-deregister.json http://localhost:8500/v1/catalog/deregister `

**Re-register Service & Node**

` curl --request PUT --data @external.json localhost:8500/v1/catalog/register ` 

**External-Node health check is missing**

```
$ curl localhost:8500/v1/health/node/External-Node1
[
    {
        "Node": "External-Node",
        "CheckID": "service:Python1",
        "Name": "tcp-check",
        "Status": "passing",
        "Notes": "",
        "Output": "TCP connect 192.168.64.32:80: Success",
        "ServiceID": "Python-HTTP1",
        "ServiceName": "Python",
        "ServiceTags": [],
        "Type": "",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {
            "Interval": "30s",
            "TCP": "192.168.64.32:80"
        },
        "CreateIndex": 3632,
        "ModifyIndex": 3642
    }
]

```

**Expected behavior**
In absence of this bug, Consul ESM should do health checks for nodes once we re-register the nodes, and do the real-time update of catalog. 

**Environment:** 
- Product Version:
  Checked with consul-esm version v0.6.0 and v0.5.0 

- Server configuration file(s) and read output of any relevant mount/role/etc configuration: 
   Have attached configuration files and read output above.

**Is there a workaround?**
For consul-esm to pick re-registered node health check again, we had to re-run consul-esm agent.

[edit: changed "External-Node1" to "External-Node" in deregistration to match up with earlier name usage]

### PR DESCRIPTION
**Pull request by eikenb**
Bug desc: Deregister a node then re-registering it quickly would lead to a node without coordiates, etc. for a time as there is a timed based status entry that needed to expire before the re-registration would be complete with coordinates and all.

This change clears out those saved status along with the making sure the inflight ping tracking is also cleared. So that the re-registered node can be processed normally.

Fixes #119

### CODE REVIEW

File: coordinate.go [hunk 1]
```diff
@@ -418,3 +420,36 @@ func pingNode(addr string, method string) (time.Duration, error) {
 		return 0, pingErr
 	}
 }
+
+// Needed for cases of unregister->reregister, so the newly re-registered
+// node doesn't use the old status (which would stay for timed duration).
+// Also clear an inflightPings flag if present.
+func (a *Agent) checkNodeTracking(inCh nodeChannel) nodeChannel {
+	outCh := make(chan []*api.Node)
+	oldNodes := []*api.Node{}
```
Comment (hashi-derek) [inline coordinate.go:429]: Does `oldNodes` need to be referenced outside of the goroutine? If not, wouldn't it be better to place it inside of the func scope to ensure that multithreading issues are less likely for future authors?

File: coordinate.go [hunk 2]
```diff
@@ -22,15 +22,16 @@ const (
...
+
+// The maximum time to wait for a ping to complete.
+var MaxRTT = 5 * time.Second
 
 // updateCoords is a long running goroutine that attempts to ping all external nodes
 // once per CoordinateUpdateInterval and update their statuses in Consul.
-func (a *Agent) updateCoords(nodeCh <-chan []*api.Node) {
+func (a *Agent) updateCoords(nodeCh nodeChannel) {
 	// Wait for the first node ordering
+	nodeCh = a.checkNodeTracking(nodeCh)
```
Comment (hashi-derek) [inline coordinate.go:34]: This is a nice way to introduce a fix without modifying too much of the existing code. Should we be concerned about the complexity of introducing another channel and goroutine into the system, however? From my understanding, it appears as if we could do the following, but perhaps I'm missing something:

```
func (a *Agent) checkNodeTracking(nodes []*api.Node) {...}
...
select {
case newNodes := <-nodeCh:
        a.checkNodeTracking(newNodes)
	if len(newNodes) != len(nodes) {
```

Also, maybe something that implies a state change is occurring would be more understandable for the method name. Something like `clearDeregisteredNodeTracking()` might be easier for other authors.

File: coordinate.go [hunk 3]
```diff
@@ -418,3 +420,36 @@ func pingNode(addr string, method string) (time.Duration, error) {
...
+
+// Needed for cases of unregister->reregister, so the newly re-registered
+// node doesn't use the old status (which would stay for timed duration).
+// Also clear an inflightPings flag if present.
+func (a *Agent) checkNodeTracking(inCh nodeChannel) nodeChannel {
+	outCh := make(chan []*api.Node)
+	oldNodes := []*api.Node{}
+	go func() {
+		for nodes := range inCh {
+			inUse := make(map[string]bool, len(oldNodes))
```
Comment (hashi-derek) [inline coordinate.go:432]: This might not necessarily warrant a change, but do we typically use bool-maps for sets? I've seen a few go projects use the empty struct instead to avoid problems with future authors assigning `false` into the map.

Comment (eikenb) [reply coordinate.go:432]: If this were a longer lived map, on the struct or something I might agree. IMO for local scoped use cases misuse isn't really a risk and a boolean reads better.

File: coordinate.go (hunk 1 above)
Comment (eikenb) [reply coordinate.go:429]: Didn't catch that when I migrated it into a goroutine.
:+1:

File: coordinate.go (hunk 2 above)
Comment (eikenb) [reply coordinate.go:34]: I originally had a call almost just like that but given the architecture of ESM I thought I'd start with patterns more inspired by CSP and data flow programming and focus on the channels as a primary interaction point. We'll see how it goes.
